# Generated by Django 2.2.4 on 2019-08-22 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themainapp', '0003_auto_20190822_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='ImageId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='themainapp.Images'),
        ),
        migrations.AlterField(
            model_name='liked',
            name='commentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='themainapp.Comments'),
        ),
    ]
