# Generated by Django 2.2.4 on 2019-08-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themainapp', '0004_auto_20190822_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_reply',
            new_name='Parent',
        ),
    ]
